from app.schemas.base import BaseSchema, PaginatedResponse, MessageResponse, IDResponse
from app.schemas.auth import (
    RegisterRequest,
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    UserResponse,
    UserUpdateRequest,
    ChangePasswordRequest,
)
from app.schemas.workspace import (
    WorkspaceCreate,
    WorkspaceUpdate,
    WorkspaceResponse,
    WorkspaceMemberResponse,
    InviteMemberRequest,
    UpdateMemberRoleRequest,
)
from app.schemas.brand_voice import BrandVoiceCreate, BrandVoiceUpdate, BrandVoiceResponse
from app.schemas.content import (
    ContentGenerationRequest,
    ContentRewriteRequest,
    ContentSummarizeRequest,
    ContentPostCreate,
    ContentPostUpdate,
    ContentPostResponse,
    ContentGenerationResponse,
    ScheduleContentRequest,
)
from app.schemas.ads import (
    AdAccountCreate,
    AdAccountResponse,
    CampaignResponse,
    CampaignMetricsResponse,
    AdsDashboardResponse,
    SyncAdsRequest,
)
from app.schemas.ai_gateway import (
    AIProvider,
    AIGenerationRequest,
    AIGenerationResponse,
    AIProviderStatus,
)
from app.schemas.alerts import AIAlertResponse, AlertsListResponse, MarkAlertReadRequest

__all__ = [
    "BaseSchema",
    "PaginatedResponse",
    "MessageResponse",
    "IDResponse",
    "RegisterRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "UserResponse",
    "UserUpdateRequest",
    "ChangePasswordRequest",
    "WorkspaceCreate",
    "WorkspaceUpdate",
    "WorkspaceResponse",
    "WorkspaceMemberResponse",
    "InviteMemberRequest",
    "UpdateMemberRoleRequest",
    "BrandVoiceCreate",
    "BrandVoiceUpdate",
    "BrandVoiceResponse",
    "ContentGenerationRequest",
    "ContentRewriteRequest",
    "ContentSummarizeRequest",
    "ContentPostCreate",
    "ContentPostUpdate",
    "ContentPostResponse",
    "ContentGenerationResponse",
    "ScheduleContentRequest",
    "AdAccountCreate",
    "AdAccountResponse",
    "CampaignResponse",
    "CampaignMetricsResponse",
    "AdsDashboardResponse",
    "SyncAdsRequest",
    "AIProvider",
    "AIGenerationRequest",
    "AIGenerationResponse",
    "AIProviderStatus",
    "AIAlertResponse",
    "AlertsListResponse",
    "MarkAlertReadRequest",
]
