'use client'

import jsPDF from 'jspdf'
import { autoTable } from 'jspdf-autotable'
import { Campaign, Keyword, ContentPost, Competitor } from './types'

// Color palette matching the app's vibrant theme
const COLORS = {
  purple: [168, 85, 247] as [number, number, number],
  pink: [236, 72, 153] as [number, number, number],
  blue: [59, 130, 246] as [number, number, number],
  emerald: [16, 185, 129] as [number, number, number],
  orange: [249, 115, 22] as [number, number, number],
  dark: [10, 10, 15] as [number, number, number],
  card: [18, 18, 26] as [number, number, number],
  text: [240, 240, 255] as [number, number, number],
  gray: [136, 136, 170] as [number, number, number],
}

function addHeader(doc: jsPDF, title: string, subtitle: string) {
  // Gradient bar at top
  doc.setFillColor(...COLORS.purple)
  doc.rect(0, 0, 210, 18, 'F')
  doc.setFillColor(...COLORS.pink)
  doc.rect(140, 0, 70, 18, 'F')

  // Logo text
  doc.setFontSize(14)
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.text('Marketing Hub', 14, 12)

  // Date
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const date = new Date().toLocaleDateString('vi-VN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(date, 196, 12, { align: 'right' })

  // Title section
  doc.setFillColor(18, 18, 26)
  doc.rect(0, 18, 210, 24, 'F')

  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text(title, 14, 33)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...COLORS.gray)
  doc.text(subtitle, 14, 41)
}

function addFooter(doc: jsPDF, pageNum: number, total: number) {
  const pageHeight = doc.internal.pageSize.height
  doc.setFillColor(18, 18, 26)
  doc.rect(0, pageHeight - 12, 210, 12, 'F')
  doc.setFontSize(8)
  doc.setTextColor(...COLORS.gray)
  doc.text('Marketing Hub - Generated by AI', 14, pageHeight - 4)
  doc.text(`Page ${pageNum} / ${total}`, 196, pageHeight - 4, { align: 'right' })
}

function fmt(n: number): string {
  if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M'
  if (n >= 1000) return (n / 1000).toFixed(0) + 'K'
  return n.toString()
}

export function exportDashboardPDF(campaigns: Campaign[], posts: ContentPost[]) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  addHeader(doc, 'Dashboard Report', 'Tong quan hieu suat marketing')

  // KPI Summary section
  const totalRevenue = campaigns.reduce((s, c) => s + c.revenue, 0)
  const totalSpend = campaigns.reduce((s, c) => s + c.spent, 0)
  const totalConversions = campaigns.reduce((s, c) => s + c.conversions, 0)
  const roas = totalSpend > 0 ? (totalRevenue / totalSpend).toFixed(2) : '0'

  // KPI boxes (2x2 grid)
  const kpis = [
    { label: 'Total Reach', value: '555K', color: COLORS.purple },
    { label: 'Total Revenue', value: `$${fmt(totalRevenue)}`, color: COLORS.emerald },
    { label: 'Conversions', value: fmt(totalConversions), color: COLORS.blue },
    { label: 'Avg ROAS', value: `${roas}x`, color: COLORS.orange },
  ]

  let y = 50
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('KPI Overview', 14, y)
  y += 6

  kpis.forEach((kpi, i) => {
    const x = 14 + (i % 2) * 93
    const boxY = y + Math.floor(i / 2) * 22
    doc.setFillColor(18, 18, 26)
    doc.roundedRect(x, boxY, 88, 18, 3, 3, 'F')
    doc.setFillColor(...kpi.color)
    doc.roundedRect(x, boxY, 4, 18, 2, 0, 'F')
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...kpi.color)
    doc.text(kpi.value, x + 10, boxY + 11)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.gray)
    doc.text(kpi.label, x + 10, boxY + 16)
  })

  y += 50

  // Campaign performance table
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Campaign Performance', 14, y)
  y += 4

  autoTable(doc, {
    startY: y,
    head: [['Campaign', 'Platform', 'Status', 'Spent', 'Revenue', 'ROAS', 'Conv.']],
    body: campaigns.map(c => [
      c.name,
      c.platform,
      c.status,
      `$${fmt(c.spent)}`,
      `$${fmt(c.revenue)}`,
      `${c.spent > 0 ? (c.revenue / c.spent).toFixed(2) : 0}x`,
      c.conversions.toString(),
    ]),
    headStyles: { fillColor: COLORS.purple, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [18, 18, 26], textColor: COLORS.text, fontSize: 8 },
    alternateRowStyles: { fillColor: [26, 26, 46] },
    styles: { lineColor: [255, 255, 255], lineWidth: 0.1 },
    margin: { left: 14, right: 14 },
  })

  // Recent posts
  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Recent Content', 14, finalY)

  autoTable(doc, {
    startY: finalY + 4,
    head: [['Title', 'Status', 'Platforms', 'Date']],
    body: posts.slice(0, 6).map(p => [
      p.title,
      p.status,
      p.platform.join(', '),
      p.scheduledDate || p.publishedDate || p.createdAt,
    ]),
    headStyles: { fillColor: COLORS.blue, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [18, 18, 26], textColor: COLORS.text, fontSize: 8 },
    alternateRowStyles: { fillColor: [26, 26, 46] },
    styles: { lineColor: [255, 255, 255], lineWidth: 0.1 },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc, 1, 1)
  doc.save(`marketing-hub-dashboard-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportCampaignsPDF(campaigns: Campaign[]) {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' })

  addHeader(doc, 'Campaign Report', 'Chi tiet hieu suat tat ca chien dich')

  const totalBudget = campaigns.reduce((s, c) => s + c.budget, 0)
  const totalSpent = campaigns.reduce((s, c) => s + c.spent, 0)
  const totalRevenue = campaigns.reduce((s, c) => s + c.revenue, 0)
  const totalConv = campaigns.reduce((s, c) => s + c.conversions, 0)

  // Summary row
  let y = 50
  const summaries = [
    { label: 'Total Budget', value: `$${fmt(totalBudget)}`, color: COLORS.purple },
    { label: 'Total Spent', value: `$${fmt(totalSpent)}`, color: COLORS.orange },
    { label: 'Total Revenue', value: `$${fmt(totalRevenue)}`, color: COLORS.emerald },
    { label: 'Total Conversions', value: fmt(totalConv), color: COLORS.blue },
    { label: 'Overall ROAS', value: `${totalSpent > 0 ? (totalRevenue / totalSpent).toFixed(2) : 0}x`, color: COLORS.pink },
  ]

  summaries.forEach((s, i) => {
    const x = 14 + i * 55
    doc.setFillColor(18, 18, 26)
    doc.roundedRect(x, y, 50, 16, 3, 3, 'F')
    doc.setFillColor(...s.color)
    doc.roundedRect(x, y, 3, 16, 1.5, 0, 'F')
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...s.color)
    doc.text(s.value, x + 8, y + 9)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...COLORS.gray)
    doc.text(s.label, x + 8, y + 14)
  })

  y += 24

  autoTable(doc, {
    startY: y,
    head: [['Campaign Name', 'Platform', 'Status', 'Budget', 'Spent', '%', 'Impressions', 'Clicks', 'CTR', 'Conv.', 'Revenue', 'ROAS']],
    body: campaigns.map(c => {
      const ctr = c.impressions > 0 ? ((c.clicks / c.impressions) * 100).toFixed(2) + '%' : '0%'
      const roasVal = c.spent > 0 ? (c.revenue / c.spent).toFixed(2) + 'x' : '0x'
      const pct = c.budget > 0 ? Math.round((c.spent / c.budget) * 100) + '%' : '0%'
      return [c.name, c.platform, c.status, `$${fmt(c.budget)}`, `$${fmt(c.spent)}`, pct, fmt(c.impressions), fmt(c.clicks), ctr, c.conversions.toString(), `$${fmt(c.revenue)}`, roasVal]
    }),
    headStyles: { fillColor: COLORS.orange, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
    bodyStyles: { fillColor: [18, 18, 26], textColor: COLORS.text, fontSize: 7.5 },
    alternateRowStyles: { fillColor: [26, 26, 46] },
    styles: { lineColor: [255, 255, 255], lineWidth: 0.1 },
    margin: { left: 14, right: 14 },
    columnStyles: { 11: { textColor: COLORS.emerald } },
  })

  addFooter(doc, 1, 1)
  doc.save(`campaigns-report-${new Date().toISOString().split('T')[0]}.pdf`)
}

export function exportSEOPDF(keywords: Keyword[], competitors: Competitor[]) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  addHeader(doc, 'SEO Report', 'Keyword tracking & Competitor analysis')

  let y = 50
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Keyword Rankings', 14, y)
  y += 4

  autoTable(doc, {
    startY: y,
    head: [['Keyword', 'Rank', 'Prev Rank', 'Change', 'Search Vol.', 'Difficulty', 'URL']],
    body: keywords.map(k => {
      const diff = k.previousRank - k.currentRank
      const change = diff > 0 ? `+${diff}` : diff < 0 ? `${diff}` : '-'
      return [k.keyword, `#${k.currentRank}`, `#${k.previousRank}`, change, fmt(k.searchVolume), `${k.difficulty}/100`, k.url || '-']
    }),
    headStyles: { fillColor: COLORS.blue, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [18, 18, 26], textColor: COLORS.text, fontSize: 8 },
    alternateRowStyles: { fillColor: [26, 26, 46] },
    styles: { lineColor: [255, 255, 255], lineWidth: 0.1 },
    margin: { left: 14, right: 14 },
    didParseCell: (data) => {
      if (data.column.index === 3 && data.section === 'body') {
        const val = String(data.cell.text[0])
        if (val.startsWith('-') && val !== '-') {
          data.cell.styles.textColor = COLORS.pink
        } else if (val.startsWith('+')) {
          data.cell.styles.textColor = COLORS.emerald
        }
      }
    },
  })

  const kwFinalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...COLORS.text)
  doc.text('Competitor Analysis', 14, kwFinalY)

  autoTable(doc, {
    startY: kwFinalY + 4,
    head: [['Competitor', 'Website', 'Domain Auth.', 'Est. Traffic', 'Keywords', 'Notes']],
    body: competitors.map(c => [c.name, c.website, c.domainAuthority.toString(), fmt(c.estimatedTraffic), fmt(c.keywords), c.notes || '-']),
    headStyles: { fillColor: COLORS.purple, textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fillColor: [18, 18, 26], textColor: COLORS.text, fontSize: 8 },
    alternateRowStyles: { fillColor: [26, 26, 46] },
    styles: { lineColor: [255, 255, 255], lineWidth: 0.1 },
    margin: { left: 14, right: 14 },
  })

  addFooter(doc, 1, 1)
  doc.save(`seo-report-${new Date().toISOString().split('T')[0]}.pdf`)
}
